### ISSUE TITLE
Ativa no /r/BrasildoB pls

### ISSUE THREAD

**Issue by picsi** [CaioWzy/NemLiNemLereiBot#1]
vai la nunca te pedi nada https://www.reddit.com/r/brasildob

**Comment by CaioWzy** [comment]
Pronto, obrigado pelo interesse =)  
Saiba que no momento ele só resume as notícias do g1 e estadão, existem alguns problemas que encontrei durante a execução do bot e estou corrigindo aos poucos.

**Comment by picsi** [comment]
Valeu! Por que só esses dois?

**Comment by CaioWzy** [comment]
Eu fiz o bot de forma que pudéssemos criar plugins para suportar mais
páginas, os plugins ajudam o bot a extrair o conteúdo do artigo para ser
resumido. Como escrevi o bot há pouco tempo, ainda existem vários bugs que
precisam ser corrigidos e estou fazendo aos poucos, quando estiver mais
estável eu poderei focar nos plugins.
